_target_: rbyte.viz.loggers.RerunLogger
_convert_: all
_recursive_: false
application_id: kion
recording_name:
- meta
- input_id
spawn: true
schema:
  /hawk_back/left/image_rect_resized/log_time:
    _target_: rerun.TimeColumn
    timestamp:
    - data
    - /hawk_back/left/image_rect_resized/log_time
    dtype: datetime64[ns]
  hawk_back:
  - _target_: rerun.Image.columns
    buffer:
    - data
    - hawk_back
  - static: true
    _target_: rerun.Image.from_fields
    format:
      _target_: rerun.components.ImageFormat
      height: 600
      width: 960
      color_model: RGB
      channel_datatype: u8
  /cmd_vel/linear.x:
  - _target_: rerun.Scalars.columns
    scalars:
    - data
    - /cmd_vel/linear.x
